# Generated by Django 2.0 on 2017-12-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
